version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../backend/output:/app/output
      - ../backend/storage:/app/storage
      - ../descargas:/app/descargas
    environment:
      - PORT=3001
      - AI_URL=http://host.docker.internal:1234/v1/chat/completions
      - AI_MODEL=qwen3

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "8978:8978"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
